# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirwatch < Formula
  desc "dirwatch is a simple, standalone tool that watches a path and runs a command whenever it
detects a matching event.
"
  homepage ""
  version "0.0.7"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/dirwatch/releases/download/v0.0.7/dirwatch_Darwin_x86_64.tar.gz"
      sha256 "58fc1744d050ac5522b0013de5e72c56d03d50aaa1e68896a1446b2799814723"

      def install
        bin.install "dirwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hay-kot/dirwatch/releases/download/v0.0.7/dirwatch_Darwin_arm64.tar.gz"
      sha256 "de0792068d03aadd044b6f0b43c092d290dbbc460c59fca37e58a409fc028f70"

      def install
        bin.install "dirwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/dirwatch/releases/download/v0.0.7/dirwatch_Linux_x86_64.tar.gz"
      sha256 "3137d7d8a16fcf76198d463a2e8b291b60a702d5ae1752b06c157a54cfe0c3a1"

      def install
        bin.install "dirwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hay-kot/dirwatch/releases/download/v0.0.7/dirwatch_Linux_arm64.tar.gz"
      sha256 "b4d3ac4d9ab7091329a8569f6790cf667571775d8973a75bddc95f7a5e442694"

      def install
        bin.install "dirwatch"
      end
    end
  end

  service do
    run [opt_bin/"dirwatch", "watch"]
    keep_alive true
  end

  test do
    system "#{bin}/dirwatch version"
  end
end
